# TODO: Update path, train, val, test

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/alp/AVTPerception/February/AVT-Perception/datasets/signs  # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/train  # val images (relative to 'path') 4 images
test: images/train # test images (optional)

# Classes (46 COCO classes)
names:

    0: addedLane 
    1: slow
    2: curveLeft 
    3: speedLimit15
    4: curveRight 
    5: speedLimit25
    6: dip 
    7: speedLimit30
    8: doNotEnter 
    9: speedLimit35
    10: doNotPass
    11: speedLimit40
    12: intersection 
    13: speedLimit45
    14: keepRight 
    15: speedLimit50
    16: laneEnds
    17: speedLimit55
    18: merge
    19: speedLimit65
    20: noLeftTurn
    21: speedLimitUrdbl
    22: noRightTurn 
    23: stop
    24: pedestrianCrossing
    25: stopAhead
    26: rampSpeedAdvisory20
    27: thruMergeLeft
    28: rampSpeedAdvisory35 
    29: thruMergeRight
    30: rampSpeedAdvisory40
    31: thruTrafficMergeLeft
    32: rampSpeedAdvisory45 
    33: truckSpeedLimit55
    34: rampSpeedAdvisory50
    35: turnLeft
    36: rampSpeedAdvisoryUrdbl
    37: turnRight
    38: rightLaneMustTurn
    39: yield
    40: roundabout
    41: yieldAhead
    42: school
    43: zoneAhead25
    44: schoolSpeedLimit25
    45: zoneAhead45
    46: signalAhead